Repository MicrosoftDocs/IntuneDocs, pull requests merged in 2018-07, with the labels that each got.

#1173 Update byod-technology-decisions.md
  intune/byod-technology-decisions.md
Labels: assigned-to-author, doc-bug, triaged

#856 Staging Citrix instructions
  intune/app-sdk.md
Labels: assigned-to-author, doc-bug, triaged

#1132 Add minimum required Visual Studio version for Windows
  intune/app-sdk-xamarin.md
Labels: assigned-to-author, triaged

#1188 Update app-configuration-policies-managed-app.md
  intune/app-configuration-policies-managed-app.md
Labels: assigned-to-author, doc-enhancement, triaged

#1196 Update app-protection-policy-settings-android.md
  intune/app-protection-policy-settings-android.md
Labels: assigned-to-author, doc-bug, triaged

#1282 Update conditional-access-exchange-create.md
  intune/conditional-access-exchange-create.md
Labels: Change sent to author, do-not-merge, microsoft-intune
