Repository MicrosoftDocs/IntuneDocs, pull requests merged in 2018-08, with the labels that each got.

#1281 Update device-restrictions-android.md
  intune/device-restrictions-android.md
Labels: do-not-merge

#1171 Updated group membership description
  intune/help-desk-operators.md
Labels: assigned-to-author, doc-bug, triaged

#1249 Update app-wrapper-prepare-android.md
  intune/app-wrapper-prepare-android.md
Labels: do-not-merge

#1336 Don't tell users they need to copy the Packager volume contents locally
  intune/app-wrapper-prepare-ios.md
Labels: assigned-to-author

#1345 Update app-modern-authentication-block.md
  intune/app-modern-authentication-block.md
Labels: assigned-to-author
